services:
  - type: web
    name: claimr-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        fromDatabase:
          name: claimr_db_4tyc
          property: connectionString
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ADMIN_SECRET_KEY
        generateValue: true
